# Generated by Django 4.1.2 on 2023-12-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
