# Generated by Django 4.1.2 on 2023-12-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_utilisateur_image_utilisateur_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password2',
            field=models.CharField(default=1234, max_length=30),
        ),
    ]
