# Generated by Django 4.1.2 on 2023-12-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_utilisateur_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(default='David', max_length=30),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(default='Kamano', max_length=30),
        ),
    ]
