# Generated by Django 4.1.2 on 2023-11-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=30)),
                ('prix', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('quantite', models.IntegerField()),
                ('image', models.ImageField(upload_to='%y%m%d')),
                ('date_commande', models.DateField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionproduits.categorie')),
            ],
        ),
    ]
