# Generated by Django 5.0.3 on 2024-03-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='image',
            field=models.ImageField(blank=True, upload_to='%y%m%d'),
        ),
    ]
