# Generated by Django 4.1.2 on 2023-11-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produits',
            old_name='date_commande',
            new_name='date',
        ),
    ]
