# Generated by Django 5.0.3 on 2024-03-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduits', '0003_alter_commande_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date_commanede',
            new_name='date_commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='livré',
            field=models.BooleanField(default=False),
        ),
    ]
