# Generated by Django 5.0.3 on 2024-03-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduits', '0004_rename_date_commanede_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(auto_now=True),
        ),
    ]
