# Generated by Django 4.1.2 on 2023-12-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduits', '0005_remove_cart_order_date_remove_cart_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='ordered',
        ),
    ]
