# Generated by Django 4.1.2 on 2023-12-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduits', '0010_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('suject', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
