# Generated by Django 4.1.2 on 2023-12-31 15:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionproduits', '0012_cart_order_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Card',
        ),
    ]
