# Generated by Django 5.0.3 on 2024-03-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
