# Generated by Django 5.0.3 on 2024-03-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0003_alter_utilisateur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='token',
            field=models.CharField(default='abcdefghi', max_length=100),
            preserve_default=False,
        ),
    ]
